### ISSUE TITLE
Field 'policy_name' invalid error

### ISSUE THREAD

**Issue by azilber** [higanworks/knife-zero#95]
Seems Policyfile.rb is a hard requirement.  knife zero no longer works for me.

This is the error:
`Creating new client for db-master
Creating new node for db-master
ERROR: The data in your request was invalid
Response: Field 'policy_name' invalid`

Chef Development Kit Version: 0.10.0
chef-client version: 12.8.1
berks version: 4.0.1
kitchen version: 1.4.2

I've cleared out ~/.chefdk, reinstalled chefdk, etc.

I've added use_policyfile false to knife.rb with no effect.

Of some interest, is running knife zero diagnose:

`
Zero Bootstrap Config
====================
---
:encrypt: false
:run_list: []
:policy_name: 
:policy_group: local
:tags: []
:first_boot_attributes: 
:first_boot_attributes_from_file: 
:host_key_verify: true
:remote_chef_zero_port: 
:bootstrap_converge: true
:appendix_config: 
:use_sudo: false
`

I have no idea where policy_group is coming from...

**Comment by azilber** [comment]
Reverting seems to help:  chef gem install knife-zero -v 1.10.2

**Comment by sawanoboly** [comment]
Could you remove `validation_key` from `knife.rb` ? I heard a report that the resolve it

**Comment by sawanoboly** [comment]
I could not reproduce your issue by chefdk_0.12.0-1_amd64.deb with knife-zero (1.15.3) .

`knife zero bootstrap 192.168.33.32 -N target -x vagrant `

workstation to target on test-kitchen.

```
---
driver:
  name: vagrant
  box: opscode-ubuntu-14.04

provisioner:
  name: shell

platforms:
  - name: workstation
    driver:
      network:
        - ["private_network", {ip: "192.168.33.31"}]
  - name: target
    driver:
      network:
        - ["private_network", {ip: "192.168.33.32"}]

suites:
  - name: default
    run_list:
    attributes:
```


related #93
